[project]
src = "src"
out = "out"
dot_env = ".env"
dependencies = ["snekmate"]

[networks.pyevm]
is_zksync = false

[networks.arbitrum]
url = "https://arb1.arbitrum.io/rpc"
prompt_live = true
save_to_db = true

[networks.anvil]
url = "http://127.0.0.1:8545"
prompt_live = false
save_to_db = false
chain_id = 31337
